apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-prod
  labels:
    app: taskflow-api
    managed-by: kelompok8
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Boleh buat 1 Pod ekstra sementara update
      maxUnavailable: 0  # Jangan matikan Pod lama sebelum yang baru siap
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret  # Secret untuk pull image dari GHCR (privat)
      containers:
        - name: taskflow-api
          image: hashicorp/http-echo:latest
          args:
            - "-text=Halo dari TaskFlow v1!"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
